---
dock_applications:
  - /System/Applications/Launchpad.app
  - /System/Applications/System Preferences.app
  - /System/Applications/App Store.app
  - /System/Applications/Messages.app
  - /Applications/WhatsApp.app
  - /Applications/Slack.app
  - /Applications/Postico.app
  - /Applications/Insomnia.app
  - /Applications/iTerm.app
  - /Applications/Google Chrome.app
  - /Applications/Cursor.app
  - /Applications/Qobuz.app
  - /Applications/Linear.app
  - /Applications/1Password.app
