---
dock_applications:
  - /System/Applications/Apps.app
  - /System/Applications/System Settings.app
  - /System/Applications/App Store.app
  - /System/Applications/Messages.app
  - /Applications/WhatsApp.app
  - /Applications/Slack.app
  - /Applications/Postico 2.app
  - /Applications/Insomnia.app
  - /Applications/iTerm.app
  - /Applications/Google Chrome.app
  - /Applications/Cursor.app
  - /Applications/Qobuz.app
  - /Applications/Linear.app
  - /Applications/1Password.app
