---
- name: Iterm2 - Don’t display the annoying prompt when quitting iTerm
  community.general.osx_defaults:
    domain: com.googlecode.iterm2
    key: PromptOnQuit
    type: bool
    value: false
    state: present

- name: Iterm2 - Set the custom preferences directory
  community.general.osx_defaults:
    domain: com.googlecode.iterm2
    key: PrefsCustomFolder
    type: string
    value: "~/.local/share/chezmoi/iterm2"
    state: present

- name: Iterm2 - Use the custom preferences directory
  community.general.osx_defaults:
    domain: com.googlecode.iterm2
    key: LoadPrefsFromCustomFolder
    type: bool
    value: true
    state: present
