---
- name: Iterm2 - Don’t display the annoying prompt when quitting iTerm
  community.general.osx_defaults:
    domain: com.googlecode.iterm2
    key: PromptOnQuit
    type: bool
    value: false
    state: present
