---
# General
- name: General - Set language and text formats 1/4
  community.general.osx_defaults:
    domain: NSGlobalDomain
    key: AppleLanguages
    type: array
    value:
      - fr-FR
      - en-FR
    state: present

- name: General - Set language and text formats 2/4
  community.general.osx_defaults:
    domain: NSGlobalDomain
    key: AppleLocale
    type: string
    value: fr_FR
    state: present

- name: General - Set language and text formats 3/4
  community.general.osx_defaults:
    domain: NSGlobalDomain
    key: AppleMeasurementUnits
    type: string
    value: Centimeters
    state: present

- name: General - Set language and text formats 4/4
  community.general.osx_defaults:
    domain: NSGlobalDomain
    key: AppleMetricUnits
    type: bool
    value: true
    state: present

- name: General - Disable automatic capitalization as it’s annoying when typing code
  community.general.osx_defaults:
    domain: NSGlobalDomain
    key: NSAutomaticCapitalizationEnabled
    type: bool
    value: false
    state: present

- name: General - Disable smart dashes as they’re annoying when typing code
  community.general.osx_defaults:
    domain: NSGlobalDomain
    key: NSAutomaticDashSubstitutionEnabled
    type: bool
    value: false
    state: present

- name: General - Disable automatic period substitution as it’s annoying when typing code
  community.general.osx_defaults:
    domain: NSGlobalDomain
    key: NSAutomaticPeriodSubstitutionEnabled
    type: bool
    value: false
    state: present

- name: General - Disable smart quotes as they’re annoying when typing code
  community.general.osx_defaults:
    domain: NSGlobalDomain
    key: NSAutomaticQuoteSubstitutionEnabled
    type: bool
    value: false
    state: present

- name: General - Disable auto-correct
  community.general.osx_defaults:
    domain: NSGlobalDomain
    key: NSAutomaticSpellingCorrectionEnabled
    type: bool
    value: false
    state: present

- name: General - Enable Tab in modal dialogs
  community.general.osx_defaults:
    domain: NSGlobalDomain
    key: AppleKeyboardUIMode
    type: int
    value: 3
    state: present

# Keyboard
- name: Keyboard - Maximize key repetition speed
  community.general.osx_defaults:
    domain: NSGlobalDomain
    key: KeyRepeat
    type: int
    value: 2
    state: present

- name: Keyboard - Minimize key repetition delay
  community.general.osx_defaults:
    domain: NSGlobalDomain
    key: InitialKeyRepeat
    type: int
    value: 15
    state: present

# Trackpad
- name: Trackpad - Enable tap to click for this user and for the login screen
  community.general.osx_defaults:
    domain: "{{ item.domain }}"
    key: "{{ item.key }}"
    type: "{{ item.type }}"
    value: "{{ item.value }}"
    host: "{{ item.host | default(omit) }}"
    state: present
  with_items:
    - { domain: com.apple.driver.AppleBluetoothMultitouch.trackpad, key: Clicking, type: int, value: 1 }
    - { domain: com.apple.AppleBluetoothMultitouch.trackpad, key: Clicking, type: bool, value: true }
    - { domain: NSGlobalDomain, key: com.apple.mouse.tapBehavior, type: int, host: currentHost, value: 1 }
    - { domain: NSGlobalDomain, key: com.apple.mouse.tapBehavior, type: int, value: 1 }

# Dark mode
- name: Dark mode - Dark mode (macOS >= 10.14)
  community.general.osx_defaults:
    domain: NSGlobalDomain
    key: AppleInterfaceStyle
    type: string
    value: Dark
    state: present

# Screenshots
- name: Screenshots - Create screenshots directory
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/Screenshots"
    state: directory
    mode: 0700

- name: Screenshots - Save screenshots to a directory
  community.general.osx_defaults:
    domain: com.apple.screencapture
    key: location
    type: string
    value: "{{ ansible_env.HOME }}/Screenshots"
    state: present

- name: Screenshots - Save screenshots as png
  community.general.osx_defaults:
    domain: com.apple.screencapture
    key: type
    type: string
    value: png
    state: present

# Volumes
- name: Volumes - Avoid creating .DS_Store files on network volumes
  community.general.osx_defaults:
    domain: com.apple.desktopservices
    key: DSDontWriteNetworkStores
    type: bool
    value: true
    state: present

- name: Volumes - Avoid creating .DS_Store files on USB volumes
  community.general.osx_defaults:
    domain: com.apple.desktopservices
    key: DSDontWriteUSBStores
    type: bool
    value: true
    state: present

# Screen saver
# - name: Screen saver - Require password immediately after sleep or screen saver begins 1/2
#   community.general.osx_defaults:
#     domain: com.apple.screensaver
#     key: askForPassword
#     type: int
#     value: 1
#     state: present

# - name: Screen saver - Require password immediately after sleep or screen saver begins 2/2
#   community.general.osx_defaults:
#     domain: com.apple.screensaver
#     key: askForPasswordDelay
#     type: int
#     value: 0
#     state: present

# Battery
# - name: Battery - Show battery percentage
#   community.general.osx_defaults:
#     domain: com.apple.menuextra.battery
#     key: ShowPercent
#     type: bool
#     value: true
#     state: present

# iCloud
# - name: iCloud - Save to disk (not icloud) by default
#   community.general.osx_defaults:
#     domain: NSGlobalDomain
#     key: NSDocumentSaveNewDocumentsToCloud
#     type: bool
#     value: false
#     state: present

# Dashboard
# - name: Dashboard - Disable Dashboard
#   community.general.osx_defaults:
#     domain: com.apple.dashboard
#     key: mcx-disabled
#     type: bool
#     value: true
#     state: present

# Menu bar
# - name: Menu bar - Setup
#   community.general.osx_defaults:
#     domain: com.apple.systemuiserver
#     key: menuExtras
#     type: array
#     value:
#       - "/System/Library/CoreServices/Menu Extras/Clock.menu"
#       - "/System/Library/CoreServices/Menu Extras/Battery.menu"
#       - "/System/Library/CoreServices/Menu Extras/AirPort.menu"
#       - "/System/Library/CoreServices/Menu Extras/Bluetooth.menu"
#       - "/System/Library/CoreServices/Menu Extras/Volume.menu"
#       - "/System/Library/CoreServices/Menu Extras/TimeMachine.menu"
#     state: present
#   notify: killall systemuiserver

# - name: Menu bar - Show volume
#   community.general.osx_defaults:
#     domain: com.apple.systemuiserver
#     key: "NSStatusItem Visible com.apple.menuextra.volume"
#     type: bool
#     value: true
#     state: present
#   notify: killall systemuiserver

# - name: Menu bar - Show Time Machine
#   community.general.osx_defaults:
#     domain: com.apple.systemuiserver
#     key: "NSStatusItem Visible com.apple.menuextra.TimeMachine"
#     type: bool
#     value: true
#     state: present
#   notify: killall systemuiserver
