---
- name: Setup Clock
  ansible.builtin.include_tasks: _clock.yml

- name: Setup Dock
  ansible.builtin.include_tasks: _dock.yml

- name: Setup Finder
  ansible.builtin.include_tasks: _finder.yml

- name: Setup iTerm2
  ansible.builtin.include_tasks: _iterm2.yml

- name: Setup Safari
  ansible.builtin.include_tasks: _safari.yml

- name: Setup Settings
  ansible.builtin.include_tasks: _settings.yml

- name: Setup TextEdit
  ansible.builtin.include_tasks: _textedit.yml
