---

- hosts: all
  roles:
    - prepare
    - brew
    - app-store
    - dock
    - osx-defaults
    - asdf
    - dotfiles
    # - ssh
    # - vim
    # - iterm
    # - vscode

    # - base
    # - git
    # - dev
    # - mac
    # - gem
    # - npm
  user: elindorath
