---
- name: Debug
  hosts: localhost
  vars:
    dataset:
      - toto: 1
      - toto: 2

  tasks:
    - name: Print env for item 1
      ansible.builtin.command: "echo {{ item.toto }}"
      loop: "{{ dataset }}"
      register: result

    - name: dashboard
      ansible.builtin.shell: "[ \"{{ item.toto }}\" = \"1\" ]"
      loop: "{{ dataset }}"
      loop_control:
        index_var: i
      register: res
      ignore_errors: true
      changed_when:
        - res.rc != 0

    - name: Debug
      ansible.builtin.debug:
        var: "res.results[{{ i }}]"
      loop: "{{ dataset }}"
      loop_control:
        index_var: i
