---
extension_program_mapping:
  # ----- Cursor ----- #
  .babelrc: com.todesktop.230313mzl4w4u92
  .bash_profile: com.todesktop.230313mzl4w4u92
  .bashrc: com.todesktop.230313mzl4w4u92
  .c: com.todesktop.230313mzl4w4u92
  .cfg: com.todesktop.230313mzl4w4u92
  .coffee: com.todesktop.230313mzl4w4u92
  .conf: com.todesktop.230313mzl4w4u92
  .cpp: com.todesktop.230313mzl4w4u92
  .css: com.todesktop.230313mzl4w4u92
  .d.ts: com.todesktop.230313mzl4w4u92
  .db: com.todesktop.230313mzl4w4u92
  .editorconfig: com.todesktop.230313mzl4w4u92
  .env: com.todesktop.230313mzl4w4u92
  .envrc: com.todesktop.230313mzl4w4u92
  .eslintrc: com.todesktop.230313mzl4w4u92
  .fish: com.todesktop.230313mzl4w4u92
  .gitignore: com.todesktop.230313mzl4w4u92
  .go: com.todesktop.230313mzl4w4u92
  .h: com.todesktop.230313mzl4w4u92
  .hbs: com.todesktop.230313mzl4w4u92
  .hpp: com.todesktop.230313mzl4w4u92
  .js: com.todesktop.230313mzl4w4u92
  .json: com.todesktop.230313mzl4w4u92
  .json5: com.todesktop.230313mzl4w4u92
  .jsonc: com.todesktop.230313mzl4w4u92
  .jsx: com.todesktop.230313mzl4w4u92
  .less: com.todesktop.230313mzl4w4u92
  .liquid: com.todesktop.230313mzl4w4u92
  .lock: com.todesktop.230313mzl4w4u92
  .log: com.todesktop.230313mzl4w4u92
  .markdown: com.todesktop.230313mzl4w4u92
  .md: com.todesktop.230313mzl4w4u92
  .mod: com.todesktop.230313mzl4w4u92
  .php: com.todesktop.230313mzl4w4u92
  .properties: com.todesktop.230313mzl4w4u92
  .ps1: com.todesktop.230313mzl4w4u92
  .pug: com.todesktop.230313mzl4w4u92
  .py: com.todesktop.230313mzl4w4u92
  .rb: com.todesktop.230313mzl4w4u92
  .sass: com.todesktop.230313mzl4w4u92
  .scala: com.todesktop.230313mzl4w4u92
  .scss: com.todesktop.230313mzl4w4u92
  .sh: com.todesktop.230313mzl4w4u92
  .snap: com.todesktop.230313mzl4w4u92
  .sql: com.todesktop.230313mzl4w4u92
  .swift: com.todesktop.230313mzl4w4u92
  .tmpl: com.todesktop.230313mzl4w4u92
  .toml: com.todesktop.230313mzl4w4u92
  .tool-versions: com.todesktop.230313mzl4w4u92
  .ts: com.todesktop.230313mzl4w4u92
  .tsx: com.todesktop.230313mzl4w4u92
  .twig: com.todesktop.230313mzl4w4u92
  .vue: com.todesktop.230313mzl4w4u92
  .xhtml: com.todesktop.230313mzl4w4u92
  .xml: com.todesktop.230313mzl4w4u92
  .yaml: com.todesktop.230313mzl4w4u92
  .yml: com.todesktop.230313mzl4w4u92
  .zlogin: com.todesktop.230313mzl4w4u92
  .zprofile: com.todesktop.230313mzl4w4u92
  .zshenv: com.todesktop.230313mzl4w4u92
  .zshrc: com.todesktop.230313mzl4w4u92
  Brewfile: com.todesktop.230313mzl4w4u92
  Dockerfile: com.todesktop.230313mzl4w4u92
  Gemfile: com.todesktop.230313mzl4w4u92
  Makefile: com.todesktop.230313mzl4w4u92
  Procfile: com.todesktop.230313mzl4w4u92
  Rakefile: com.todesktop.230313mzl4w4u92
  # ----- Iina ----- #
  .avi: com.colliderli.iina
  .mkv: com.colliderli.iina
  .mov: com.colliderli.iina
  .mp3: com.colliderli.iina
  .mp4: com.colliderli.iina
  .ogg: com.colliderli.iina
  .wav: com.colliderli.iina
  .webm: com.colliderli.iina
  # ----- Preview ----- #
  .bmp: com.apple.Preview
  .jpeg: com.apple.Preview
  .jpg: com.apple.Preview
  .pdf: com.apple.Preview
  .png: com.apple.Preview
  .tif: com.apple.Preview
  .tiff: com.apple.Preview
  # ----- The Unarchiver ----- #
  .7z: com.macpaw.site.theunarchiver
  .bz2: com.macpaw.site.theunarchiver
  .gtar: com.macpaw.site.theunarchiver
  .gz: com.macpaw.site.theunarchiver
  .lz: com.macpaw.site.theunarchiver
  .rar: com.macpaw.site.theunarchiver
  .tar: com.macpaw.site.theunarchiver
  .tar.gz: com.macpaw.site.theunarchiver
  .xz: com.macpaw.site.theunarchiver
  .zip: com.macpaw.site.theunarchiver
