---
- name: Ask for 1Password service account token
  ansible.builtin.pause:
    prompt: What is your 1Password service account token?
    echo: true
  register: asked_op_service_account_token
  when:
    - ansible_env.OP_SERVICE_ACCOUNT_TOKEN is not defined

- name: Set OP_SERVICE_ACCOUNT_TOKEN fact
  ansible.builtin.set_fact:
    op_service_account_token: "{{ ansible_env.OP_SERVICE_ACCOUNT_TOKEN | default(asked_op_service_account_token.stdout) }}"

- name: Get chezmoi source path
  ansible.builtin.command: "chezmoi source-path"
  register: chezmoi_source_path
  changed_when:
    - chezmoi_source_path.rc != 0

- name: Check chezmoi directory existence
  ansible.builtin.stat:
    path: "{{ chezmoi_source_path.stdout }}"
  register: chezmoi_source_directory

- name: Install chezmoi source
  ansible.builtin.command: "chezmoi init git@github.com:elindorath/dotfiles.git --apply --branch chezmoi"
  environment:
    OP_SERVICE_ACCOUNT_TOKEN: "{{ op_service_account_token }}"
  when:
    - not chezmoi_source_directory.stat.exists

- name: Update chezmoi source
  ansible.builtin.command: "chezmoi update"
  environment:
    OP_SERVICE_ACCOUNT_TOKEN: "{{ op_service_account_token }}"
  when:
    - chezmoi_source_directory.stat.exists
