---
- name: Get chezmoi source path
  ansible.builtin.command: "chezmoi source-path"
  register: chezmoi_source_path
  changed_when:
    - chezmoi_source_path.rc != 0

- name: Check chezmoi directory existence
  ansible.builtin.stat:
    path: "{{ chezmoi_source_path.stdout }}"
  register: chezmoi_source_directory

- name: Install chezmoi source
  ansible.builtin.command: "chezmoi init git@github.com:elindorath/dotfiles.git --apply --branch chezmoi"
  environment:
    BW_SESSION: "{{ bw_session }}"
  when:
    - not chezmoi_source_directory.stat.exists

- name: Update chezmoi source
  ansible.builtin.command: "chezmoi update"
  environment:
    BW_SESSION: "{{ bw_session }}"
  when:
    - chezmoi_source_directory.stat.exists
