---
- name: Remove all items from the Dock
  ansible.builtin.command: "/usr/local/opt/dockutil --remove all"
  changed_when: true
  notify: killall dock

- name: Set the default Dock items
  ansible.builtin.command: "/usr/local/opt/dockutil --add {{ item }} --no-restart"
  with_items: "{{ dock_applications }}"
  changed_when: true
  notify: killall dock
