---
- name: Install asdf plugins
  ansible.builtin.command: "asdf plugin add {{ item.name }} {{ item.repository }}"
  args:
    creates: "{{ ansible_env.HOME }}/.asdf/plugins/{{ item.name }}"
  loop: "{{ asdf_plugins_to_install }}"
  register: result_plugin
  failed_when:
    - result_plugin.rc != 0
    - '"already added" not in result_plugin.stderr'

- name: Install asdf plugin tool versions
  ansible.builtin.command: "asdf install {{ item.0.name }} {{ item.1 }}"
  args:
    creates: "{{ ansible_env.HOME }}/.asdf/installs/{{ item.0.name }}"
  environment: "{{ item.0.env | default({}) }}"
  with_subelements:
    - "{{ asdf_plugins_to_install }}"
    - versions

- name: Set tool-versions path
  ansible.builtin.set_fact:
    tool_version_path: "{{ (ansible_env.HOME, '.tool-versions') | path_join }}"

- name: Get ~/.tool-versions state
  ansible.builtin.set_fact:
    tool_versions: "{{ dict(lookup('file', tool_version_path) | split('\n') | map('split', ' ')) }}"

- name: Set asdf plugin tool global versions
  ansible.builtin.command: "asdf global {{ item.name }} {{ item.global }}"
  loop: "{{ asdf_plugins_to_install }}"
  register: result_global_version
  changed_when:
    - result_global_version.rc == 0
    - tool_versions[item.name] is not defined

- name: Get direnv line from ~/.tool-versions
  ansible.builtin.set_fact:
    direnv_line: "{{ lookup('file', tool_version_path) | regex_search('direnv .+') }}"

- name: Remove direnv line from ~/.tool-versions
  ansible.builtin.lineinfile:
    path: "{{ tool_version_path }}"
    line: "{{ direnv_line }}"
    state: absent

- name: Append direnv line at the beginning of ~/.tool-versions
  ansible.builtin.lineinfile:
    path: "{{ tool_version_path }}"
    line: "{{ direnv_line }}"
    state: present
    insertbefore: BOF
  when:
    - direnv_line | length > 0

- name: Execute after install hooks
  ansible.builtin.command: "{{ item.after_install }}"
  loop: "{{ asdf_plugins_to_install }}"
  when:
    - item.after_install is defined
