---
- name: killall dock
  ansible.builtin.command: killall Dock
  become: true
  ignore_errors: true

- name: killall finder
  ansible.builtin.command: killall Finder
  become: true
  ignore_errors: true

- name: killall systemuiserver
  ansible.builtin.command: killall SystemUIServer
  become: true
  ignore_errors: true
