---
- name: killall dock
  ansible.builtin.command: killall Dock
  ignore_errors: true

- name: killall finder
  ansible.builtin.command: killall Finder
  ignore_errors: true

- name: killall systemuiserver
  ansible.builtin.command: killall SystemUIServer
  ignore_errors: true
