---
- name: Update and upgrade packages for Homebrew
  community.general.homebrew:
    update_homebrew: yes
    upgrade_all: yes

- name: Tap brew repos
  community.general.homebrew_tap:
    state: present
    name: "{{ homebrew_repositories_to_tap }}"

- name: Install homebrew packages
  community.general.homebrew:
    name: "{{ homebrew_packages_to_install }}"
    state: present

- name: Install homebrew casks
  homebrew_cask:
    name: "{{ homebrew_casks_to_install }}"
    state: present
